import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:provider/provider.dart';
import 'package:dio/dio.dart'; // import dio
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart'; // Firebase Core
import 'firebase_options.dart'; // Auto-generated by FlutterFire
import 'data/services/api_service.dart';
import 'presentation/providers/auth_provider.dart';
import 'presentation/screens/login_screen.dart';
import 'presentation/screens/home_screen.dart';
import 'providers/service_request_provider.dart';
import 'providers/dashboard_provider.dart';
import 'providers/inventory_provider.dart';
import 'providers/customer_provider.dart';
import 'providers/user_provider.dart';
import 'providers/attendance_provider.dart';
import 'providers/pos_provider.dart';
import 'providers/challan_provider.dart';
import 'providers/job_provider.dart';
import 'providers/finance_provider.dart'; // Import FinanceProvider
import 'providers/technician_provider.dart'; // Import TechnicianProvider
import 'providers/audit_provider.dart'; // Import AuditProvider
import 'providers/admin_notification_provider.dart'; // Import AdminNotificationProvider
import 'core/api/dio_client.dart'; // Restored

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<Dio>(create: (_) {
          final dio = Dio(BaseOptions(
            baseUrl: 'http://localhost:5083', // ApiConstants.baseUrl
            connectTimeout: const Duration(seconds: 15),
            receiveTimeout: const Duration(seconds: 15),
            headers: {
              'Content-Type': 'application/json',
              'Accept': 'application/json',
            },
          ));
          
          if (kIsWeb) {
            (dio.httpClientAdapter as dynamic).withCredentials = true;
          }
          return dio;
        }),
        Provider(create: (context) => ApiService(context.read<Dio>())),
        Provider(create: (context) => DioClient(context.read<Dio>())),
        ChangeNotifierProvider(create: (context) => AuthProvider(context.read<ApiService>())),
        ChangeNotifierProvider(create: (context) => ServiceRequestProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => DashboardProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => InventoryProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => CustomerProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => UserProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => AttendanceProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => POSProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => ChallanProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => JobProvider(context.read<DioClient>())),
        ChangeNotifierProvider(create: (context) => FinanceProvider(context.read<DioClient>())), // Register FinanceProvider
        ChangeNotifierProvider(create: (context) => TechnicianProvider(context.read<DioClient>())), // Register TechnicianProvider
        ChangeNotifierProvider(create: (context) => AuditProvider(context.read<DioClient>())), // Register AuditProvider
        ChangeNotifierProvider(create: (context) => AdminNotificationProvider(context.read<DioClient>())), // Real-time notifications
      ],
      child: MaterialApp(
        title: 'Promise Admin',
        scrollBehavior: AppScrollBehavior(),
        debugShowCheckedModeBanner: false,
        theme: _buildTheme(),
        home: const AuthWrapper(),
      ),
    );
  }

  ThemeData _buildTheme() {
    return ThemeData(
      colorScheme: ColorScheme.fromSeed(
        seedColor: Colors.blue,
        primary: Colors.blue.shade700,
        secondary: Colors.blue.shade500,
      ),
      useMaterial3: true,
      textTheme: GoogleFonts.interTextTheme().copyWith(
        displayLarge: GoogleFonts.inter(fontWeight: FontWeight.bold),
        displayMedium: GoogleFonts.inter(fontWeight: FontWeight.bold),
        displaySmall: GoogleFonts.inter(fontWeight: FontWeight.bold),
        headlineLarge: GoogleFonts.inter(fontWeight: FontWeight.bold),
        headlineMedium: GoogleFonts.inter(fontWeight: FontWeight.w700),
        headlineSmall: GoogleFonts.inter(fontWeight: FontWeight.w700),
        titleLarge: GoogleFonts.inter(fontWeight: FontWeight.w600),
        titleMedium: GoogleFonts.inter(fontWeight: FontWeight.w600),
        titleSmall: GoogleFonts.inter(fontWeight: FontWeight.w600),
        bodyLarge: GoogleFonts.inter(fontWeight: FontWeight.w500),
        bodyMedium: GoogleFonts.inter(fontWeight: FontWeight.w500),
      ),
      appBarTheme: const AppBarTheme(
        centerTitle: true,
        elevation: 0,
        backgroundColor: Colors.white,
        foregroundColor: Colors.black87,
        titleTextStyle: TextStyle(
          color: Colors.black87,
          fontSize: 18,
          fontWeight: FontWeight.bold,
        ),
      ),
      scaffoldBackgroundColor: Colors.grey.shade50, // Slightly off-white for premium feel
    );
  }
}

class AuthWrapper extends StatefulWidget {
  const AuthWrapper({super.key});

  @override
  State<AuthWrapper> createState() => _AuthWrapperState();
}

class _AuthWrapperState extends State<AuthWrapper> {
  @override
  void initState() {
    super.initState();
    // Check auth status on app start
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<AuthProvider>().checkAuth();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<AuthProvider>(
      builder: (context, auth, child) {
        if (auth.isInitializing) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }

        if (auth.isAuthenticated) {
          return const HomeScreen();
        }

        return const LoginScreen();
      },
    );
  }
}

class AppScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
      };

  @override
  ScrollPhysics getScrollPhysics(BuildContext context) {
    return const BouncingScrollPhysics();
  }
}
