import { storage } from "./storage.js";
import type { InsertSystemModule } from "../shared/schema.js";

export const DEFAULT_MODULES: InsertSystemModule[] = [
    // --- CORE MODULES (Phase 1) ---
    {
        id: "jobs",
        name: "Job Tickets",
        description: "Core repair tracking and job management system.",
        category: "operations",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: true,
        isCore: true,
        displayOrder: 10,
        icon: "Ticket",
        portalScope: "admin,corporate,technician",
    },
    {
        id: "service_requests",
        name: "Service Requests",
        description: "Intake pipeline for customer self-service and triage.",
        category: "operations",
        enabledAdmin: true,
        enabledCustomer: true,
        enabledCorporate: true,
        enabledTechnician: false,
        isCore: true,
        displayOrder: 20,
        icon: "ClipboardList",
        portalScope: "admin,customer,corporate",
    },
    {
        id: "pos",
        name: "Point of Sale",
        description: "Sales and checkout interface.",
        category: "finance",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        isCore: true,
        displayOrder: 30,
        icon: "ShoppingCart",
        portalScope: "admin",
    },
    {
        id: "inventory",
        name: "Inventory",
        description: "Stock management and serialized parts tracking.",
        category: "operations",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        isCore: true,
        displayOrder: 40,
        icon: "PackageSearch",
        portalScope: "admin",
    },
    {
        id: "customers",
        name: "Customers",
        description: "Customer relationship database.",
        category: "people",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        isCore: true,
        displayOrder: 50,
        icon: "UsersRound",
        portalScope: "admin",
    },
    {
        id: "users",
        name: "User Management",
        description: "Staff account administration.",
        category: "people",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        isCore: true,
        displayOrder: 60,
        icon: "ShieldAlert",
        portalScope: "admin",
    },
    {
        id: "settings",
        name: "System Settings",
        description: "Global system configuration.",
        category: "system",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        isCore: true,
        displayOrder: 70,
        icon: "Settings",
        portalScope: "admin",
    },
    {
        id: "challans",
        name: "Challans",
        description: "Device movement logistics and transfer records.",
        category: "operations",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: true,
        enabledTechnician: false,
        displayOrder: 80,
        icon: "Truck",
        portalScope: "admin,corporate",
    },
    {
        id: "finance_petty_cash",
        name: "Petty Cash",
        description: "Daily cash drawer tracking.",
        category: "finance",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 90,
        icon: "Banknote",
        portalScope: "admin",
    },
    {
        id: "finance_dues",
        name: "Due Records",
        description: "Tracking outstanding payments.",
        category: "finance",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 100,
        icon: "Receipt",
        portalScope: "admin",
    },
    {
        id: "dashboard",
        name: "Dashboard",
        description: "High-level system KPIs and overview.",
        category: "system",
        enabledAdmin: true,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 10,
        icon: "LayoutDashboard",
        portalScope: "admin,corporate",
    },
    {
        id: "notifications",
        name: "Notifications",
        description: "System alerts and user notifications.",
        category: "system",
        enabledAdmin: true,
        enabledCustomer: true,
        enabledCorporate: true,
        enabledTechnician: true,
        displayOrder: 110,
        icon: "Bell",
        portalScope: "admin,customer,corporate,technician",
    },

    // --- NON-CORE MODULES (Phase 2/3) ---
    {
        id: "corporate",
        name: "Corporate B2B Clients",
        description: "Business-to-Business services.",
        category: "b2b",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 120,
        icon: "Building2",
        portalScope: "admin,corporate",
    },
    {
        id: "corporate_messages",
        name: "Corporate Messaging",
        description: "Communication with corporate clients.",
        category: "b2b",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 130,
        icon: "MessageSquare",
        dependencies: '["corporate"]',
        portalScope: "admin,corporate",
    },
    {
        id: "corporate_billing",
        name: "Corporate Billing",
        description: "Consolidated billing for B2B accounts.",
        category: "b2b",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 140,
        icon: "FileSpreadsheet",
        dependencies: '["corporate"]',
        portalScope: "admin,corporate",
    },
    {
        id: "attendance",
        name: "Staff Attendance",
        description: "Time and attendance tracking.",
        category: "people",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 150,
        icon: "Clock",
        portalScope: "admin",
    },
    {
        id: "salary_hr",
        name: "Salary & HR",
        description: "Payroll and human resources management.",
        category: "people",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 160,
        icon: "BriefcaseBusiness",
        portalScope: "admin",
    },
    {
        id: "cashier",
        name: "Cashier Dashboard",
        description: "Dedicated view for handling payments only.",
        category: "finance",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 170,
        icon: "Calculator",
        portalScope: "admin",
    },
    {
        id: "reports",
        name: "Work Reports",
        description: "Comprehensive reporting and exports.",
        category: "system",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 180,
        icon: "FileBarChart",
        portalScope: "admin",
    },
    {
        id: "pickup",
        name: "Pickup Schedule",
        description: "Scheduling device collection from customers.",
        category: "operations",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 190,
        icon: "CalendarRange",
        portalScope: "admin",
    },
    {
        id: "technician_view",
        name: "Technician Dashboard",
        description: "Dedicated portal for technician workflows.",
        category: "operations",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 200,
        icon: "Wrench",
        portalScope: "admin,technician",
    },
    {
        id: "orders",
        name: "Shop Orders",
        description: "E-commerce and online part orders.",
        category: "finance",
        enabledAdmin: false,
        enabledCustomer: true,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 210,
        icon: "ShoppingBag",
        portalScope: "admin,customer",
    },
    {
        id: "warranty_claims",
        name: "Warranty Claims",
        description: "Processing RMAs and external warranties.",
        category: "operations",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 220,
        icon: "ShieldCheck",
        portalScope: "admin",
    },
    {
        id: "purchasing",
        name: "Purchase Orders",
        description: "Supplier purchasing and restocking.",
        category: "operations",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 230,
        icon: "ReceiptSwiss",
        portalScope: "admin",
    },
    {
        id: "wastage",
        name: "Wastage Tracking",
        description: "Logging damaged and defective parts.",
        category: "operations",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 240,
        icon: "Trash2",
        portalScope: "admin",
    },
    {
        id: "quality_analytics",
        name: "Quality Analytics",
        description: "Supplier defect analysis.",
        category: "operations",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 250,
        icon: "LineChart",
        portalScope: "admin",
    },
    {
        id: "system_health",
        name: "System Health Monitor",
        description: "Platform performance and logs.",
        category: "system",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 260,
        icon: "Activity",
        portalScope: "admin",
    },
    {
        id: "audit_logs",
        name: "Audit Logs",
        description: "Security and compliance audit trails.",
        category: "system",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 270,
        icon: "List",
        portalScope: "admin",
    },
    {
        id: "ai_brain",
        name: "AI Brain",
        description: "Smart analytics and predictive insights.",
        category: "system",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 280,
        icon: "BrainCircuit",
        portalScope: "admin",
    },
    {
        id: "finance_refunds",
        name: "Refund Management",
        description: "Processing customer refunds.",
        category: "finance",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 290,
        icon: "Undo2",
        portalScope: "admin",
    },
    {
        id: "finance_drawer",
        name: "Cash Drawer Sessions",
        description: "Tracking shift money drops.",
        category: "finance",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 300,
        icon: "Banknote",
        portalScope: "admin",
    },
    {
        id: "inquiries",
        name: "Customer Inquiries",
        description: "Web forms and contact messages.",
        category: "people",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 310,
        icon: "HelpCircle",
        portalScope: "admin",
    },
    {
        id: "quotations",
        name: "Quotations",
        description: "Generate and manage price quotes.",
        category: "finance",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 315,
        icon: "FileText",
        portalScope: "admin",
    },
    {
        id: "customer_shop",
        name: "Online Shop",
        description: "E-commerce storefront for customers.",
        category: "finance",
        enabledAdmin: false,
        enabledCustomer: true,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 320,
        icon: "Store",
        portalScope: "customer",
    },
    {
        id: "customer_track",
        name: "Order Tracking",
        description: "Self-service tracking portal for customers.",
        category: "operations",
        enabledAdmin: false,
        enabledCustomer: false,
        enabledCorporate: false,
        enabledTechnician: false,
        displayOrder: 330,
        icon: "MapPin",
        portalScope: "customer",
    },
];

export async function seedModules() {
    console.log("Seeding system modules...");
    try {
        await storage.seedDefaultModules(DEFAULT_MODULES);
        console.log(`✅ successfully seeded ${DEFAULT_MODULES.length} system modules.`);
    } catch (err) {
        console.error("Failed to seed modules:", err);
    }
}

function isDirectSeedInvocation() {
    const entry = process.argv[1]?.replace(/\\/g, "/");
    return typeof entry === "string" && /(?:^|\/)seed-modules\.(?:ts|js|cjs|mjs)$/.test(entry);
}

if (isDirectSeedInvocation()) {
    seedModules().catch(console.error);
}
