import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from "react";

export type CustomerLang = "en" | "bn";

const STORAGE_KEY = "customerLanguage";

const translations = {
  // ── Bottom dock ──
  "dock.home":        { en: "Home",     bn: "হোম" },
  "dock.shop":        { en: "Shop",     bn: "শপ" },
  "dock.repair":      { en: "Repair",   bn: "রিপেয়ার" },
  "dock.track":       { en: "Track",    bn: "ট্র্যাক" },
  "dock.profile":     { en: "Profile",  bn: "প্রোফাইল" },

  // ── Mobile hero ──
  "hero.eyebrow":     { en: "Promise Electronics",           bn: "প্রমিজ ইলেকট্রনিক্স" },
  "hero.title":       { en: "TV repair made simple",         bn: "সহজে TV সার্ভিস" },
  "hero.toggle":      { en: "বাংলা",                          bn: "EN" },
  "hero.badge":       { en: "Trusted TV repair in Dhaka",    bn: "ঢাকায় বিশ্বস্ত TV সার্ভিস" },
  "hero.text":        { en: "Problem with your TV? We can help.", bn: "আপনার TV-তে সমস্যা? আমরা সাহায্য করব।" },
  "hero.subtitle":    { en: "Book repair, get a quote, or track your job in a few taps.", bn: "রিপেয়ার বুক করুন, কোটেশন নিন, বা কাজ ট্র্যাক করুন।" },
  "hero.repair":      { en: "Book Repair",   bn: "রিপেয়ার বুক" },
  "hero.track":       { en: "Track Job",     bn: "জব ট্র্যাক" },
  "hero.quote":       { en: "Get a quick quote", bn: "দ্রুত কোটেশন নিন" },
  "hero.aria":        { en: "Switch language to Bangla", bn: "Switch language to English" },

  // ── Quick actions ──
  "qa.bookRepair":    { en: "Book Repair",       bn: "রিপেয়ার বুক" },
  "qa.scheduleService": { en: "Schedule service", bn: "নতুন সার্ভিস" },
  "qa.trackJob":      { en: "Track Job",          bn: "জব ট্র্যাক" },
  "qa.statusUpdates": { en: "Status updates",     bn: "স্ট্যাটাস দেখুন" },
  "qa.support":       { en: "Support",            bn: "সাপোর্ট" },
  "qa.getHelp":       { en: "Get help",           bn: "সাহায্য নিন" },
  "qa.shopParts":     { en: "Shop Parts",         bn: "পার্টস শপ" },
  "qa.buyParts":      { en: "Buy parts",          bn: "পার্টস কিনুন" },

  // ── Home page ──
  "home.hello":       { en: "Hello",              bn: "হ্যালো" },
  "home.help":        { en: "How can we help?",   bn: "কীভাবে সাহায্য করতে পারি?" },
  "home.activeRepair":{ en: "Active Repair",      bn: "চলমান মেরামত" },
  "home.viewDetails": { en: "View Details",       bn: "বিস্তারিত দেখুন" },
  "home.yourTv":      { en: "Your TV",            bn: "আপনার TV" },
  "home.noDisplay":   { en: "No Display",         bn: "ডিসপ্লে নেই" },
  "home.backlight":   { en: "Backlight Issue",    bn: "ব্যাকলাইট সমস্যা" },
  "home.soundIssue":  { en: "Sound Issue",        bn: "সাউন্ড সমস্যা" },
  "home.screenCrack": { en: "Screen Crack",       bn: "স্ক্রিন ক্র্যাক" },
  "home.powerIssue":  { en: "Power Issue",        bn: "পাওয়ার সমস্যা" },
  "home.otherIssue":  { en: "Other Issue",        bn: "অন্যান্য সমস্যা" },

  // ── Shop ──
  "shop.title":       { en: "Parts & Accessories", bn: "পার্টস এবং এক্সেসরিজ" },
  "shop.eyebrow":     { en: "Parts Store",         bn: "পার্টস স্টোর" },
  "shop.subtitle":    { en: "Find genuine TV parts, accessories, and service-ready items.", bn: "আসল TV পার্টস, এক্সেসরিজ এবং সার্ভিস আইটেম খুঁজুন।" },
  "shop.items":       { en: "items",               bn: "আইটেম" },
  "shop.safeCheckout": { en: "Safe checkout",      bn: "নিরাপদ চেকআউট" },
  "shop.search":      { en: "Search products...",  bn: "পণ্য খুঁজুন..." },
  "shop.filters":     { en: "Filters",             bn: "ফিল্টার" },
  "shop.showing":     { en: "Showing",             bn: "দেখাচ্ছে" },
  "shop.results":     { en: "results",             bn: "ফলাফল" },
  "shop.sortBy":      { en: "Sort by",              bn: "সাজান" },
  "shop.sortPopularity": { en: "Popularity",        bn: "জনপ্রিয়তা" },
  "shop.sortPriceLowHigh": { en: "Price: Low to High", bn: "দাম: কম থেকে বেশি" },
  "shop.sortPriceHighLow": { en: "Price: High to Low", bn: "দাম: বেশি থেকে কম" },
  "shop.sortNewest":   { en: "Newest Arrivals",     bn: "নতুন এসেছে" },
  "shop.categories":  { en: "Categories",          bn: "ক্যাটাগরি" },
  "shop.priceRange":  { en: "Price Range",         bn: "দামের পরিসর" },
  "shop.availability": { en: "Availability",       bn: "স্টক অবস্থা" },
  "shop.inStock":     { en: "In Stock",            bn: "স্টকে আছে" },
  "shop.lowStock":    { en: "Low Stock",           bn: "স্টক কম" },
  "shop.max":         { en: "Max",                 bn: "সর্বোচ্চ" },
  "shop.for":         { en: "for",                 bn: "এর জন্য" },
  "shop.productDetails": { en: "Product Details",  bn: "পণ্যের বিস্তারিত" },
  "shop.noProducts":  { en: "No products available", bn: "কোন পণ্য পাওয়া যায়নি" },
  "shop.checkBack":   { en: "Check back later for new products.", bn: "নতুন পণ্যের জন্য পরে দেখুন।" },
  "shop.addToCart":   { en: "Add to Cart",         bn: "কার্টে যোগ করুন" },

  // ── Cart ──
  "cart.empty":       { en: "Your Cart is Empty",  bn: "আপনার কার্ট খালি" },
  "cart.emptyDesc":   { en: "Add some products to your cart and they will appear here.", bn: "আপনার কার্টে পণ্য যোগ করুন, এখানে দেখা যাবে।" },
  "cart.continue":    { en: "Continue Shopping",   bn: "শপিং চালিয়ে যান" },
  "cart.title":       { en: "Shopping Cart",       bn: "শপিং কার্ট" },
  "cart.clear":       { en: "Clear All",           bn: "সব মুছুন" },
  "cart.subtotal":    { en: "Subtotal",            bn: "সাবটোটাল" },
  "cart.checkout":    { en: "Proceed to Checkout",  bn: "চেকআউটে যান" },
  "cart.browsMore":   { en: "Browse More Products", bn: "আরো পণ্য দেখুন" },

  // ── Checkout ──
  "checkout.empty":   { en: "Your Cart is Empty",  bn: "আপনার কার্ট খালি" },
  "checkout.emptyDesc": { en: "Add a few products, then come back to checkout.", bn: "কিছু পণ্য যোগ করুন, তারপর চেকআউটে আসুন।" },
  "checkout.browse":  { en: "Browse Products",     bn: "পণ্য দেখুন" },
  "checkout.title":   { en: "Checkout",            bn: "চেকআউট" },
  "checkout.back":    { en: "Back to Cart",        bn: "কার্টে ফিরুন" },
  "checkout.shipping": { en: "Shipping Address",   bn: "শিপিং ঠিকানা" },
  "checkout.name":    { en: "Full Name",           bn: "পুরো নাম" },
  "checkout.phone":   { en: "Phone Number",        bn: "ফোন নম্বর" },
  "checkout.address": { en: "Address",             bn: "ঠিকানা" },
  "checkout.city":    { en: "City",                bn: "শহর" },
  "checkout.payment": { en: "Payment Method",      bn: "পেমেন্ট পদ্ধতি" },
  "checkout.cod":     { en: "Cash on Delivery",    bn: "ক্যাশ অন ডেলিভারি" },
  "checkout.orderSummary": { en: "Order Summary",  bn: "অর্ডার সারসংক্ষেপ" },
  "checkout.total":   { en: "Total",               bn: "মোট" },
  "checkout.place":   { en: "Place Order",         bn: "অর্ডার করুন" },

  // ── Track order ──
  "track.title":      { en: "Track Your Orders",   bn: "আপনার অর্ডার ট্র্যাক করুন" },
  "track.subtitle":   { en: "View the status of your orders and repair requests in real-time.", bn: "আপনার অর্ডার ও মেরামতের রিয়েল-টাইম স্ট্যাটাস দেখুন।" },
  "track.ticketLabel": { en: "Ticket number",      bn: "টিকেট নম্বর" },
  "track.ticketPlaceholder": { en: "Example: SR-000123", bn: "উদাহরণ: SR-000123" },
  "track.bookRepair": { en: "Book Repair",         bn: "রিপেয়ার বুক" },
  "track.signIn":     { en: "Sign In",             bn: "সাইন ইন" },
  "track.recentRepairs": { en: "Your recent repairs", bn: "আপনার সাম্প্রতিক মেরামত" },
  "track.heroTitle":  { en: "Track your repair",   bn: "আপনার মেরামত ট্র্যাক করুন" },
  "track.heroSubtitle": { en: "Enter ticket number to check status, or sign in if you have an account.", bn: "টিকেট নম্বর লিখে স্ট্যাটাস দেখুন, অথবা অ্যাকাউন্ট থাকলে সাইন ইন করুন।" },
  "track.trackTicket": { en: "Track ticket",        bn: "টিকেট ট্র্যাক করুন" },
  "track.noOrders":   { en: "No Orders Found",     bn: "কোনো অর্ডার পাওয়া যায়নি" },
  "track.noOrdersDesc": { en: "You haven't placed any orders or repair requests yet.", bn: "আপনি এখনো কোনো অর্ডার বা মেরামতের অনুরোধ করেননি।" },
  "track.shopNow":    { en: "Shop Now",            bn: "এখনই শপ করুন" },
  "track.repairRequest": { en: "Repair Request",   bn: "মেরামতের অনুরোধ" },
  "track.backToOrders": { en: "Back to Orders",    bn: "অর্ডারে ফিরুন" },
  "track.orderNotFound": { en: "Order Not Found",  bn: "অর্ডার পাওয়া যায়নি" },
  "track.orderNotFoundDesc": { en: "We couldn't load the details for this service. It may have been removed or you may have a connection issue.", bn: "এই সার্ভিসের তথ্য লোড করা যায়নি। এটি মুছে ফেলা হয়েছে বা সংযোগে সমস্যা হতে পারে।" },
  "track.tryAgain":   { en: "Try Again",           bn: "আবার চেষ্টা করুন" },
  "track.all":        { en: "All",                 bn: "সব" },
  "track.repairs":    { en: "Repairs",             bn: "মেরামত" },
  "track.products":   { en: "Products",            bn: "পণ্য" },
  "track.quotes":     { en: "Quotes",              bn: "কোটেশন" },

  // ── Track job (QR) ──
  "trackJob.title":   { en: "Repair Tracker",      bn: "রিপেয়ার ট্র্যাকার" },
  "trackJob.noTicket": { en: "No ticket selected",  bn: "কোনো টিকেট নির্বাচিত হয়নি" },
  "trackJob.scanQr":  { en: "Scan a QR code or open a ticket link to see the live repair status.", bn: "লাইভ মেরামত স্ট্যাটাস দেখতে একটি QR কোড স্ক্যান করুন বা টিকেট লিংক খুলুন।" },
  "trackJob.openHub": { en: "Open Tracking Hub",    bn: "ট্র্যাকিং হাব খুলুন" },

  // ── Profile ──
  "profile.greeting.morning": { en: "Good morning", bn: "শুভ সকাল" },
  "profile.greeting.afternoon": { en: "Good afternoon", bn: "শুভ অপরাহ্ন" },
  "profile.greeting.evening": { en: "Good evening",   bn: "শুভ সন্ধ্যা" },
  "profile.promiseMember": { en: "Promise Member",    bn: "প্রমিজ সদস্য" },
  "profile.totalOrders":  { en: "Total Orders",       bn: "মোট অর্ডার" },
  "profile.completed":    { en: "Completed",          bn: "সম্পন্ন" },
  "profile.repairs":      { en: "Repairs",            bn: "মেরামত" },
  "profile.warranty":     { en: "Warranty",           bn: "ওয়ারেন্টি" },
  "profile.address":      { en: "Address",            bn: "ঠিকানা" },
  "profile.support":      { en: "Support",            bn: "সাপোর্ট" },
  "profile.personalDetails": { en: "Personal Details", bn: "ব্যক্তিগত তথ্য" },
  "profile.fullName":     { en: "Full Name",          bn: "পুরো নাম" },
  "profile.phoneNumber":  { en: "Phone Number",       bn: "ফোন নম্বর" },
  "profile.notProvided":  { en: "Not provided",       bn: "প্রদান করা হয়নি" },
  "profile.memberSince":  { en: "Member Since",       bn: "সদস্য হওয়ার তারিখ" },
  "profile.recentlyJoined": { en: "Recently joined",  bn: "সম্প্রতি যোগদান" },
  "profile.repairHistory": { en: "Repair History",    bn: "মেরামত ইতিহাস" },
  "profile.active":       { en: "Active",             bn: "সক্রিয়" },
  "profile.noActive":     { en: "No Active Requests", bn: "সক্রিয় অনুরোধ নেই" },
  "profile.submitNew":    { en: "Submit New Request",  bn: "নতুন অনুরোধ জমা দিন" },
  "profile.logout":       { en: "Log out",            bn: "লগ আউট" },

  // ── My warranties ──
  "warranties.title":     { en: "My Warranties",      bn: "আমার ওয়ারেন্টি" },
  "warranties.none":      { en: "No Warranties Found", bn: "কোনো ওয়ারেন্টি পাওয়া যায়নি" },
  "warranties.noneDesc":  { en: "Warranties will appear here after your repairs are completed with warranty coverage.", bn: "ওয়ারেন্টি কভারেজসহ আপনার মেরামত সম্পন্ন হলে এখানে দেখা যাবে।" },
  "warranties.subtitle":  { en: "Service and parts coverage from your completed repairs.", bn: "সম্পন্ন মেরামতের সার্ভিস ও পার্টস কভারেজ।" },
  "warranties.active":    { en: "Active Warranties",  bn: "সক্রিয় ওয়ারেন্টি" },
  "warranties.expired":   { en: "Expired Warranties", bn: "মেয়াদোত্তীর্ণ ওয়ারেন্টি" },
  "warranties.service":   { en: "Service Warranty",   bn: "সার্ভিস ওয়ারেন্টি" },
  "warranties.parts":     { en: "Parts Warranty",     bn: "পার্টস ওয়ারেন্টি" },
  "warranties.serviceHelp": { en: "Covers repair workmanship after service.", bn: "সার্ভিসের পর কাজের ত্রুটি কভার করে।" },
  "warranties.partsHelp": { en: "Covers replaced parts, not voltage/liquid/physical damage.", bn: "বদলানো পার্টস কভার করে; ভোল্টেজ, পানি বা ভাঙা কভার করে না।" },
  "warranties.apply":     { en: "Apply Warranty",     bn: "ওয়ারেন্টি আবেদন করুন" },
  "warranties.claimTitle": { en: "Apply Warranty",    bn: "ওয়ারেন্টি আবেদন" },
  "warranties.claimType": { en: "Warranty type",      bn: "ওয়ারেন্টির ধরন" },
  "warranties.issue":     { en: "What problem are you facing?", bn: "আপনি কী সমস্যায় পড়েছেন?" },
  "warranties.issuePlaceholder": { en: "Describe what happened after the repair.", bn: "মেরামতের পর কী সমস্যা হয়েছে লিখুন।" },
  "warranties.submitClaim": { en: "Submit Claim",     bn: "আবেদন জমা দিন" },
  "warranties.claimSubmitted": { en: "Warranty claim submitted", bn: "ওয়ারেন্টি আবেদন জমা হয়েছে" },
  "warranties.terms":     { en: "Warranty Terms",     bn: "ওয়ারেন্টির শর্ত" },
  "warranties.termsDesc": { en: "Parts warranty is void for voltage, liquid, or physical damage. Service warranty covers workmanship issues only.", bn: "ভোল্টেজ, পানি বা শারীরিক ক্ষতিতে পার্টস ওয়ারেন্টি বাতিল হবে। সার্ভিস ওয়ারেন্টি শুধু কাজের ত্রুটি কভার করে।" },
  "warranties.daysLeft":  { en: "days left",          bn: "দিন বাকি" },
  "warranties.expiredOn": { en: "Expired on",         bn: "মেয়াদ শেষ" },

  // ── Support ──
  "support.eyebrow":      { en: "Customer Care",      bn: "কাস্টমার কেয়ার" },
  "support.title":        { en: "Help & Support",     bn: "হেল্প এবং সাপোর্ট" },
  "support.subtitle":     { en: "Call, message, or send a quick request to our service desk.", bn: "আমাদের সার্ভিস ডেস্কে কল, মেসেজ বা দ্রুত অনুরোধ পাঠান।" },
  "support.callUs":       { en: "Call Us",             bn: "কল করুন" },
  "support.whatsapp":     { en: "WhatsApp",            bn: "হোয়াটসঅ্যাপ" },
  "support.email":        { en: "Email",               bn: "ইমেইল" },
  "support.visitCenter":  { en: "Visit Our Center",    bn: "আমাদের সেন্টারে আসুন" },
  "support.businessHours": { en: "Business Hours",     bn: "ব্যবসায়িক সময়" },
  "support.messageDesk":  { en: "Message Desk",        bn: "মেসেজ ডেস্ক" },
  "support.sendMessage":  { en: "Send us a message",   bn: "আমাদের মেসেজ পাঠান" },
  "support.yourName":     { en: "Name",                bn: "নাম" },
  "support.yourPhone":    { en: "Phone Number",        bn: "ফোন নম্বর" },
  "support.message":      { en: "Message",             bn: "মেসেজ" },
  "support.messagePlaceholder": { en: "How can we help you?", bn: "আমরা কীভাবে সাহায্য করতে পারি?" },
  "support.send":         { en: "Send Message",        bn: "মেসেজ পাঠান" },
  "support.faq":          { en: "Frequently Asked Questions", bn: "সাধারণ জিজ্ঞাসা" },
  "support.faq1Q":        { en: "How do I track my repair?", bn: "আমি কীভাবে মেরামত ট্র্যাক করব?" },
  "support.faq1A":        { en: "You can track your repair status by entering your Job Ticket ID in the Track Order section on the home page or the dedicated tracking page.", bn: "হোম পেজের অর্ডার ট্র্যাক অংশে বা ট্র্যাকিং পেজে জব টিকেট আইডি দিয়ে মেরামতের স্ট্যাটাস দেখতে পারবেন।" },
  "support.faq2Q":        { en: "How long does TV repair take?", bn: "TV মেরামতে কত সময় লাগে?" },
  "support.faq2A":        { en: "Most repairs take 2-5 business days depending on parts availability and the issue complexity.", bn: "পার্টস পাওয়া এবং সমস্যার ধরনের ওপর নির্ভর করে বেশিরভাগ মেরামতে ২-৫ কর্মদিবস লাগে।" },
  "support.faq3Q":        { en: "Do you provide warranty?", bn: "আপনারা কি ওয়ারেন্টি দেন?" },
  "support.faq3A":        { en: "Yes. Eligible repairs include service warranty. Warranty details are shown on your invoice or warranty page.", bn: "হ্যাঁ। প্রযোজ্য মেরামতে সার্ভিস ওয়ারেন্টি থাকে। বিস্তারিত ইনভয়েস বা ওয়ারেন্টি পেজে দেখা যাবে।" },
  "support.faq4Q":        { en: "Can I request home pickup?", bn: "আমি কি বাসা থেকে পিকআপ চাইতে পারি?" },
  "support.faq4A":        { en: "Yes. You can choose home visit or pickup while booking a repair request.", bn: "হ্যাঁ। রিপেয়ার বুক করার সময় হোম ভিজিট বা পিকআপ বেছে নিতে পারবেন।" },

  // ── Login ──
  "login.brand":          { en: "Promise Electronics", bn: "প্রমিজ ইলেকট্রনিক্স" },
  "login.tagline":        { en: "Your repair account, orders, and warranty in one place", bn: "আপনার মেরামত, অর্ডার এবং ওয়ারেন্টি একই জায়গায়" },
  "login.promiseCare":    { en: "Promise Care",        bn: "প্রমিজ কেয়ার" },
  "login.customerPortal": { en: "Customer portal",     bn: "কাস্টমার পোর্টাল" },
  "login.heroTitle":      { en: "Repair updates, warranty and orders.", bn: "রিপেয়ার আপডেট, ওয়ারেন্টি ও অর্ডার।" },
  "login.heroSubtitle":   { en: "Sign in once and keep every Promise Electronics service detail close at hand.", bn: "একবার সাইন ইন করুন, সব সার্ভিস তথ্য হাতের কাছেই থাকবে।" },
  "login.passwordPlaceholder": { en: "Password",       bn: "পাসওয়ার্ড" },
  "login.confirmPasswordPlaceholder": { en: "Confirm password", bn: "পাসওয়ার্ড নিশ্চিত করুন" },
  "login.namePlaceholder": { en: "Your full name",     bn: "আপনার পুরো নাম" },
  "login.emailPlaceholder": { en: "Email optional",    bn: "ইমেইল ঐচ্ছিক" },
  "login.addressPlaceholder": { en: "Address optional", bn: "ঠিকানা ঐচ্ছিক" },
  "login.passwordMismatch": { en: "Passwords do not match.", bn: "পাসওয়ার্ড মিলছে না।" },
  "login.signIn":         { en: "Sign In",             bn: "সাইন ইন" },
  "login.register":       { en: "Register",            bn: "রেজিস্টার" },
  "login.welcomeBack":    { en: "Welcome Back",        bn: "স্বাগতম" },
  "login.signInDesc":     { en: "Sign in to your Promise Electronics account", bn: "আপনার প্রমিজ ইলেকট্রনিক্স অ্যাকাউন্টে সাইন ইন করুন" },
  "login.phone":          { en: "Phone Number",        bn: "ফোন নম্বর" },
  "login.password":       { en: "Password",            bn: "পাসওয়ার্ড" },
  "login.rememberMe":     { en: "Remember me",         bn: "মনে রাখুন" },
  "login.orContinue":     { en: "Or continue with",    bn: "অথবা এর সাথে চালিয়ে যান" },
  "login.google":         { en: "Continue with Google", bn: "গুগল দিয়ে চালিয়ে যান" },
  "login.recoveryHelp":   { en: "Need help signing in?", bn: "সাইন ইন করতে সাহায্য দরকার?" },
  "login.recoveryTitle":  { en: "Support-assisted recovery", bn: "সাপোর্টের মাধ্যমে অ্যাকাউন্ট রিকভারি" },
  "login.recoveryDesc":   { en: "We do not reset passwords automatically. Our team will verify your account and help you reset safely.", bn: "আমরা স্বয়ংক্রিয়ভাবে পাসওয়ার্ড রিসেট করি না। আমাদের টিম আপনার অ্যাকাউন্ট যাচাই করে নিরাপদে রিসেট করতে সাহায্য করবে।" },
  "login.recoveryStep1":  { en: "Share your phone or ticket number.", bn: "আপনার ফোন বা টিকেট নম্বর দিন।" },
  "login.recoveryStep2":  { en: "Support verifies your repair details.", bn: "সাপোর্ট আপনার মেরামতের তথ্য যাচাই করবে।" },
  "login.recoveryStep3":  { en: "You receive a short reset code from staff.", bn: "স্টাফের কাছ থেকে ছোট রিসেট কোড পাবেন।" },
  "login.openSupport":    { en: "Open Support",          bn: "সাপোর্ট খুলুন" },
  "login.recoveryNote":   { en: "Google sign-in is the fastest option if it is linked to your account.", bn: "আপনার অ্যাকাউন্টে গুগল যুক্ত থাকলে গুগল সাইন ইন সবচেয়ে দ্রুত।" },
  "login.backHome":       { en: "Back to Home",        bn: "হোমে ফিরুন" },
  "login.createAccount":  { en: "Create Account",      bn: "অ্যাকাউন্ট তৈরি করুন" },
  "login.joinDesc":       { en: "Join Promise Electronics today", bn: "আজই প্রমিজ ইলেকট্রনিক্সে যোগ দিন" },
  "login.fullName":       { en: "Full Name",           bn: "পুরো নাম" },
  "login.email":          { en: "Email (Optional)",    bn: "ইমেইল (ঐচ্ছিক)" },
  "login.confirmPassword": { en: "Confirm Password",   bn: "পাসওয়ার্ড নিশ্চিত করুন" },
  "login.terms":          { en: "By creating an account, you agree to our", bn: "অ্যাকাউন্ট তৈরি করে আপনি আমাদের শর্তাবলীতে সম্মত হচ্ছেন" },
  "login.termsLink":      { en: "Terms of Service",    bn: "সেবার শর্তাবলী" },
  "login.privacyLink":    { en: "Privacy Policy",      bn: "গোপনীয়তা নীতি" },

  // ── Repair / Service Wizard ──
  "repair.backToServices": { en: "Back to Services",   bn: "সার্ভিসে ফিরুন" },
  "repair.step1":         { en: "Device Info",         bn: "ডিভাইস তথ্য" },
  "repair.step2":         { en: "Contact",             bn: "যোগাযোগ" },
  "repair.step3":         { en: "Complete",             bn: "সম্পন্ন" },
  "repair.tellUs":        { en: "Tell Us About Your Device", bn: "আপনার ডিভাইস সম্পর্কে বলুন" },
  "repair.tellUsDesc":    { en: "Help us understand what needs to be repaired", bn: "কী মেরামত করতে হবে তা বুঝতে সাহায্য করুন" },
  "repair.serviceType":   { en: "Service Type",        bn: "সার্ভিসের ধরন" },
  "repair.selectService": { en: "Select a service",    bn: "একটি সার্ভিস নির্বাচন করুন" },
  "repair.tvBrand":       { en: "TV Brand",            bn: "TV ব্র্যান্ড" },
  "repair.selectBrand":   { en: "Select your TV brand", bn: "আপনার TV ব্র্যান্ড নির্বাচন করুন" },
  "repair.screenSize":    { en: "Screen Size (Inch)",  bn: "স্ক্রিন সাইজ (ইঞ্চি)" },
  "repair.selectSize":    { en: "Select size",         bn: "সাইজ নির্বাচন করুন" },
  "repair.modelNumber":   { en: "Model Number",        bn: "মডেল নম্বর" },
  "repair.mainIssue":     { en: "Main Issue",          bn: "প্রধান সমস্যা" },
  "repair.selectIssue":   { en: "What's wrong with your TV?", bn: "আপনার TV-তে কী সমস্যা?" },
  "repair.additionalDetails": { en: "Additional Details (Optional)", bn: "অতিরিক্ত বিবরণ (ঐচ্ছিক)" },
  "repair.next":          { en: "Next",                bn: "পরবর্তী" },
  "repair.previous":      { en: "Previous",            bn: "পূর্ববর্তী" },
  "repair.submit":        { en: "Submit Request",      bn: "অনুরোধ জমা দিন" },

  // ── Service wizard (mobile) ──
  "wizard.whatProblem":    { en: "What's wrong with your TV?", bn: "আপনার TV-তে কী সমস্যা?" },
  "wizard.tapOption":      { en: "Tap one option. We will ask only what is needed.", bn: "একটি অপশন ট্যাপ করুন। শুধু যা দরকার তাই জিজ্ঞেস করব।" },
  "wizard.aboutTv":        { en: "Tell us about your TV",     bn: "আপনার TV সম্পর্কে বলুন" },
  "wizard.aboutTvDesc":    { en: "Brand and size help us prepare the right technician.", bn: "ব্র্যান্ড ও সাইজ দিলে সঠিক টেকনিশিয়ান পাঠাতে পারব।" },
  "wizard.tvType":         { en: "TV type",                   bn: "TV ধরন" },
  "wizard.tvLed":          { en: "LED",                       bn: "LED" },
  "wizard.tvSmart":        { en: "Smart TV",                  bn: "স্মার্ট TV" },
  "wizard.tvAndroid":      { en: "Android TV",                bn: "অ্যান্ড্রয়েড TV" },
  "wizard.tvOled":         { en: "OLED/QLED",                 bn: "OLED/QLED" },
  "wizard.notSure":        { en: "Not sure",                  bn: "নিশ্চিত নই" },
  "wizard.brand":          { en: "Brand *",                   bn: "ব্র্যান্ড *" },
  "wizard.selectBrand":    { en: "Select brand",              bn: "ব্র্যান্ড বাছুন" },
  "wizard.size":           { en: "Size",                      bn: "সাইজ" },
  "wizard.model":          { en: "Model",                     bn: "মডেল" },
  "wizard.optional":       { en: "Optional",                  bn: "ঐচ্ছিক" },
  "wizard.photoTitle":     { en: "Photos help us diagnose faster", bn: "ছবি দিলে দ্রুত বুঝব" },
  "wizard.photoDesc":      { en: "Optional. Add a screen photo or short video.", bn: "ঐচ্ছিক। স্ক্রিনের ছবি বা ছোট ভিডিও দিন।" },
  "wizard.quotePhotoDesc": { en: "Optional. You can describe the issue now; our team may ask for photos later.", bn: "ঐচ্ছিক। সমস্যাটা লিখুন; আমাদের টিম পরে ছবি চাইতে পারে।" },
  "wizard.addPhoto":       { en: "Add photo/video",           bn: "ছবি/ভিডিও দিন" },
  "wizard.uploading":      { en: "Uploading...",              bn: "আপলোড হচ্ছে..." },
  "wizard.skipStep":       { en: "You can skip this step",    bn: "এই ধাপ এড়িয়ে যেতে পারেন" },
  "wizard.extraDetails":   { en: "Extra details",             bn: "অতিরিক্ত বিবরণ" },
  "wizard.serviceTitle":   { en: "How do you want service?",  bn: "আপনি কীভাবে সার্ভিস চান?" },
  "wizard.serviceDesc":    { en: "Choose the easiest option for you.", bn: "আপনার জন্য সহজ অপশন বেছে নিন।" },
  "wizard.homeVisit":      { en: "Home visit",                bn: "বাসা থেকে সার্ভিস" },
  "wizard.dropOff":        { en: "Drop-off",                  bn: "শপে নিয়ে আসব" },
  "wizard.callFirst":      { en: "Call me first",             bn: "আগে আমাকে কল করুন" },
  "wizard.pickupAddress":  { en: "Pickup address",            bn: "পিকআপ ঠিকানা" },
  "wizard.finalStep":      { en: "Final step",                bn: "শেষ ধাপ" },
  "wizard.finalDesc":      { en: "We need only your name and phone number.", bn: "শুধু আপনার নাম ও ফোন নম্বর দিন।" },
  "wizard.name":           { en: "Name *",                    bn: "নাম *" },
  "wizard.phone":          { en: "Phone *",                   bn: "ফোন *" },
  "wizard.summary":        { en: "Summary",                   bn: "সারসংক্ষেপ" },
  "wizard.back":           { en: "Back",                      bn: "পেছনে" },
  "wizard.continue":       { en: "Continue",                  bn: "পরবর্তী" },
  "wizard.getQuote":       { en: "Get Quote",                 bn: "কোটেশন নিন" },
  "wizard.requestService": { en: "Request Service",           bn: "সার্ভিস অনুরোধ" },
  "wizard.received":       { en: "Request received",          bn: "অনুরোধ গৃহীত" },
  "wizard.willCall":       { en: "We will call you",          bn: "আমরা আপনাকে কল করব" },
  "wizard.submitted":      { en: "Your request is submitted. Keep this ticket number.", bn: "আপনার অনুরোধ জমা হয়েছে। এই টিকেট নম্বরটি সংরক্ষণ করুন।" },
  "wizard.ticketNumber":   { en: "Ticket number",             bn: "টিকেট নম্বর" },
  "wizard.step":           { en: "Step",                      bn: "ধাপ" },
  "wizard.of":             { en: "of",                        bn: "এর" },
  "wizard.writeIssue":     { en: "Describe the problem...",   bn: "সমস্যাটা লিখুন..." },

  // ── 404 / Not found ──
  "notFound.quickLinks":  { en: "Try these quick links", bn: "এই লিংকগুলো চেষ্টা করুন" },
  "notFound.home":        { en: "Home Page",           bn: "হোম পেজ" },
  "notFound.homeDesc":    { en: "Return to the main dashboard", bn: "মূল ড্যাশবোর্ডে ফিরুন" },
  "notFound.trackRepair": { en: "Track Repair",        bn: "রিপেয়ার ট্র্যাক" },
  "notFound.trackDesc":   { en: "Check your device status", bn: "আপনার ডিভাইসের স্ট্যাটাস দেখুন" },
  "notFound.shop":        { en: "Shop",                bn: "শপ" },
  "notFound.shopDesc":    { en: "Browse latest electronics", bn: "সর্বশেষ ইলেকট্রনিক্স দেখুন" },
  "notFound.support":     { en: "Support",             bn: "সাপোর্ট" },
  "notFound.supportDesc": { en: "Get help from Daktar Vai", bn: "ডাক্তার ভাই থেকে সাহায্য নিন" },
  "notFound.error":       { en: "System Error 404",    bn: "সিস্টেম ত্রুটি ৪০৪" },
  "notFound.title":       { en: "Page Not",            bn: "পেজ পাওয়া" },
  "notFound.titleAccent": { en: "Found",               bn: "যায়নি" },
  "notFound.desc":        { en: "We couldn't locate the page you're looking for. It might have been moved, deleted, or you may have mistyped the address.", bn: "আপনি যে পেজটি খুঁজছেন তা পাওয়া যায়নি। এটি সরানো, মুছে ফেলা হয়েছে বা আপনি ঠিকানায় ভুল করেছেন।" },
  "notFound.goBack":      { en: "Go back to previous page", bn: "আগের পেজে ফিরুন" },

  // ── Auth gate (checkout etc) ──
  "auth.loginRequired":  { en: "Login Required",       bn: "লগইন প্রয়োজন" },
  "auth.loginDesc":      { en: "Sign in or create an account to complete your purchase.", bn: "আপনার কেনাকাটা সম্পন্ন করতে সাইন ইন বা অ্যাকাউন্ট তৈরি করুন।" },
  "auth.signInRegister": { en: "Sign In / Register",   bn: "সাইন ইন / রেজিস্টার" },

  // ── Order success ──
  "order.placed":        { en: "Order Placed!",        bn: "অর্ডার সম্পন্ন!" },
  "order.placedFull":    { en: "Order Placed Successfully!", bn: "অর্ডার সফলভাবে সম্পন্ন!" },
  "order.trackOrder":    { en: "Track Order",          bn: "অর্ডার ট্র্যাক করুন" },
  "order.call":          { en: "Call",                 bn: "কল করুন" },
  "order.orders":        { en: "Orders",               bn: "অর্ডার" },

  // ── Misc page strings ──
  "shop.noMatch":        { en: "No products match your filters", bn: "আপনার ফিল্টারে কোনো পণ্য মেলেনি" },
  "shop.tryAdjusting":   { en: "Try adjusting your filters.",    bn: "আপনার ফিল্টার পরিবর্তন করে দেখুন।" },
  "profile.noCompleted": { en: "No Completed Requests",         bn: "সম্পন্ন অনুরোধ নেই" },
  "profile.noCompletedOrders": { en: "No Completed Orders",     bn: "সম্পন্ন অর্ডার নেই" },
  "track.signInToTrack": { en: "Sign In to Track Orders",       bn: "অর্ডার ট্র্যাক করতে সাইন ইন করুন" },
  "support.sending":     { en: "Sending...",                     bn: "পাঠানো হচ্ছে..." },

  // ── Common ──
  "common.promiseElectronics": { en: "Promise Electronics", bn: "প্রমিজ ইলেকট্রনিক্স" },
  "common.support":      { en: "Support",              bn: "সাপোর্ট" },
  "common.details":      { en: "Details",              bn: "বিস্তারিত" },
  "common.contactUs":    { en: "Contact us",           bn: "যোগাযোগ করুন" },
  "common.clearFilters": { en: "Clear filters",        bn: "ফিল্টার মুছুন" },
  "common.previous":     { en: "Previous",             bn: "আগের" },
  "common.next":         { en: "Next",                 bn: "পরের" },
  "common.close":        { en: "Close",                bn: "বন্ধ করুন" },
  "common.and":          { en: "and",                  bn: "এবং" },

  // ── Services ──
  "services.badge":      { en: "Professional Repair Services", bn: "প্রফেশনাল রিপেয়ার সার্ভিস" },
  "services.title":      { en: "Expert TV & Electronics", bn: "দক্ষ TV ও ইলেকট্রনিক্স" },
  "services.titleAccent": { en: "Repair Services",     bn: "রিপেয়ার সার্ভিস" },
  "services.subtitle":   { en: "Get transparent pricing with no hidden fees. Request a free quote and we'll inspect your device before providing a final price.", bn: "লুকানো খরচ ছাড়া স্বচ্ছ দাম পান। ফ্রি কোটেশন নিন, আমরা চূড়ান্ত দামের আগে ডিভাইস পরীক্ষা করব।" },
  "services.freePickup": { en: "Free Pickup Available", bn: "ফ্রি পিকআপ আছে" },
  "services.warranty":   { en: "90-Day Warranty",      bn: "৯০ দিনের ওয়ারেন্টি" },
  "services.technicians": { en: "Expert Technicians",  bn: "দক্ষ টেকনিশিয়ান" },
  "services.search":     { en: "Search services...",   bn: "সার্ভিস খুঁজুন..." },
  "services.all":        { en: "All Services",         bn: "সব সার্ভিস" },
  "services.categoryLed": { en: "LED TV Repair",       bn: "LED TV মেরামত" },
  "services.categoryLcd": { en: "LCD TV Repair",       bn: "LCD TV মেরামত" },
  "services.categorySmart": { en: "Smart TV Repair",   bn: "স্মার্ট TV মেরামত" },
  "services.categoryMonitor": { en: "Monitor Repair",  bn: "মনিটর মেরামত" },
  "services.categoryProjector": { en: "Projector Repair", bn: "প্রজেক্টর মেরামত" },
  "services.showing":    { en: "Showing",              bn: "দেখাচ্ছে" },
  "services.of":         { en: "of",                   bn: "এর মধ্যে" },
  "services.services":   { en: "services",             bn: "সার্ভিস" },
  "services.failed":     { en: "Failed to load services", bn: "সার্ভিস লোড করা যায়নি" },
  "services.noMatch":    { en: "No services match your search criteria.", bn: "আপনার খোঁজ অনুযায়ী কোনো সার্ভিস মেলেনি।" },
  "services.none":       { en: "No services available at the moment.", bn: "এই মুহূর্তে কোনো সার্ভিস নেই।" },
  "services.noMatchShort": { en: "No services match your search.", bn: "আপনার খোঁজ অনুযায়ী সার্ভিস নেই।" },
  "services.noneShort":  { en: "No services available.", bn: "কোনো সার্ভিস নেই।" },
  "services.priceRange": { en: "Price Range",          bn: "দামের পরিসর" },
  "services.getQuote":   { en: "Get Quote",            bn: "কোটেশন নিন" },
  "services.processTitle": { en: "How Our Quote Process Works", bn: "আমাদের কোটেশন প্রক্রিয়া কীভাবে কাজ করে" },
  "services.processSubtitle": { en: "Get a hassle-free repair experience with our transparent pricing process", bn: "স্বচ্ছ মূল্য প্রক্রিয়ায় ঝামেলাহীন মেরামত অভিজ্ঞতা পান" },
  "services.step1Title": { en: "Request Quote",        bn: "কোটেশন নিন" },
  "services.step1Text":  { en: "Tell us about your device and the issue you're facing", bn: "আপনার ডিভাইস এবং সমস্যার কথা জানান" },
  "services.step2Title": { en: "Get Your Quote",       bn: "কোটেশন পান" },
  "services.step2Text":  { en: "We'll review and send you a price estimate", bn: "আমরা দেখে আপনাকে আনুমানিক মূল্য পাঠাব" },
  "services.step3Title": { en: "Accept & Schedule",    bn: "অনুমোদন ও সময় ঠিক করুন" },
  "services.step3Text":  { en: "Choose pickup option and schedule your service", bn: "পিকআপ অপশন বেছে সার্ভিসের সময় ঠিক করুন" },
  "services.step4Title": { en: "Get It Repaired",      bn: "মেরামত সম্পন্ন করুন" },
  "services.step4Text":  { en: "We fix your device and deliver it back to you", bn: "আমরা আপনার ডিভাইস মেরামত করে ফিরিয়ে দিই" },
  "services.unsureTitle": { en: "Not Sure Which Service You Need?", bn: "কোন সার্ভিস লাগবে নিশ্চিত নন?" },
  "services.unsureText": { en: "No problem! Submit a general quote request and our experts will diagnose your device and recommend the best solution.", bn: "সমস্যা নেই। একটি সাধারণ কোটেশন অনুরোধ পাঠান, আমাদের বিশেষজ্ঞরা ডিভাইস পরীক্ষা করে সেরা সমাধান জানাবেন।" },
  "services.freeQuote":  { en: "Get a Free Quote",     bn: "ফ্রি কোটেশন নিন" },
  "services.contactPricing": { en: "Contact for pricing", bn: "মূল্যের জন্য যোগাযোগ করুন" },
  "services.finalPrice": { en: "Final price after inspection", bn: "পরীক্ষার পরে চূড়ান্ত মূল্য" },
  "services.included":   { en: "What's Included",     bn: "যা অন্তর্ভুক্ত" },
  "services.getAQuote":  { en: "Get a Quote",         bn: "কোটেশন নিন" },
  "about.title":         { en: "About Us",            bn: "আমাদের সম্পর্কে" },
  "about.heading":       { en: "Promise Electronics", bn: "প্রমিস ইলেকট্রনিক্স" },
  "about.who":           { en: "Who We Are",          bn: "আমরা কারা" },
  "about.guidance":      { en: "Repair guidance without confusion", bn: "বিভ্রান্তি ছাড়া মেরামত নির্দেশনা" },
  "about.mission":       { en: "Mission",             bn: "লক্ষ্য" },
  "about.vision":        { en: "Vision",              bn: "দৃষ্টি" },
  "about.offer":         { en: "What We Offer",       bn: "আমরা যা দিই" },
  "about.team":          { en: "Our Team",            bn: "আমাদের টিম" },
  "about.contact":       { en: "Contact",             bn: "যোগাযোগ" },
  "about.callSupport":   { en: "Call Support",        bn: "সাপোর্টে কল করুন" },
  "about.years":         { en: "Years",               bn: "বছর" },
  "about.repairs":       { en: "Repairs",             bn: "মেরামত" },
  "about.warranty":      { en: "Warranty",            bn: "ওয়ারেন্টি" },
  "journey.title":       { en: "My Repairs",          bn: "আমার মেরামত" },
  "journey.subtitle":    { en: "See every repair journey, quote, schedule, and update in one place.", bn: "প্রতিটি মেরামত, কোটেশন, সময়সূচি ও আপডেট এক জায়গায় দেখুন।" },
  "journey.empty":       { en: "No repair journeys yet", bn: "এখনো কোনো মেরামত যাত্রা নেই" },
  "journey.emptyDesc":   { en: "Book a repair or request a quote. Your progress will appear here.", bn: "রিপেয়ার বুক করুন বা কোটেশন নিন। অগ্রগতি এখানে দেখা যাবে।" },
  "journey.startRepair": { en: "Start Repair",        bn: "রিপেয়ার শুরু করুন" },
  "journey.nextAction":  { en: "Next action",         bn: "পরবর্তী কাজ" },
  "journey.timeline":    { en: "Timeline",            bn: "টাইমলাইন" },
  "journey.schedule":    { en: "Schedule",            bn: "সময়সূচি" },
  "journey.requestSchedule": { en: "Request schedule", bn: "সময়সূচি অনুরোধ করুন" },
  "journey.reschedule":  { en: "Reschedule",          bn: "সময় বদলান" },
  "journey.acceptQuote": { en: "Accept Quote",        bn: "কোটেশন গ্রহণ করুন" },
  "journey.askQuestion": { en: "Ask Question",        bn: "প্রশ্ন করুন" },
  "journey.homePickup":  { en: "Home pickup",         bn: "বাসা থেকে পিকআপ" },
  "journey.pickupAndDelivery": { en: "Pickup & delivery", bn: "পিকআপ ও ডেলিভারি" },
  "journey.serviceCenter": { en: "Service center",    bn: "সার্ভিস সেন্টার" },
  "journey.serviceCenterVisit": { en: "Service center visit", bn: "সার্ভিস সেন্টার ভিজিট" },
  "journey.quoteOnly":   { en: "Quote only",          bn: "শুধু কোটেশন" },
  "journey.pickupTier":  { en: "Pickup tier",         bn: "পিকআপ ধরন" },
  "journey.regular":     { en: "Regular",             bn: "রেগুলার" },
  "journey.priority":    { en: "Priority",            bn: "প্রায়োরিটি" },
  "journey.emergency":   { en: "Emergency",           bn: "জরুরি" },
  "journey.pickup":      { en: "Pickup",              bn: "পিকআপ" },
  "journey.dropOff":     { en: "Drop off",            bn: "ড্রপ অফ" },
  "journey.homeVisit":   { en: "Home visit",          bn: "বাসায় ভিজিট" },
  "journey.delivery":    { en: "Delivery",            bn: "ডেলিভারি" },
  "journey.noAction":    { en: "No action needed",    bn: "কোনো কাজ বাকি নেই" },
  "journey.nextAcceptQuote": { en: "Review & Accept Quote", bn: "কোটেশন দেখুন ও গ্রহণ করুন" },
  "journey.nextRequestSchedule": { en: "Request Schedule", bn: "সময়সূচি অনুরোধ করুন" },
  "journey.nextReschedule": { en: "Reschedule Service", bn: "সময় বদলান" },
  "journey.nextAskQuestion": { en: "Ask a Question", bn: "প্রশ্ন করুন" },
  "journey.nextApproveRepair": { en: "Approve Repair", bn: "মেরামত অনুমোদন করুন" },
  "journey.address":     { en: "Address",             bn: "ঠিকানা" },
  "journey.date":        { en: "Date",                bn: "তারিখ" },
  "journey.timeWindow":  { en: "Time window",         bn: "সময়" },
  "journey.note":        { en: "Note",                bn: "নোট" },
  "journey.submit":      { en: "Submit",              bn: "জমা দিন" },
  "journey.cancel":      { en: "Cancel",              bn: "বাতিল" },
  "journey.status":      { en: "Status",              bn: "স্ট্যাটাস" },
  "journey.details":     { en: "Journey details",     bn: "যাত্রার বিস্তারিত" },
  "journey.open":        { en: "Open",                bn: "খুলুন" },
  "journey.viewMyRepairs": { en: "View My Repairs",   bn: "আমার মেরামত দেখুন" },
  "journey.privateNote": { en: "Private admin note",  bn: "প্রাইভেট অ্যাডমিন নোট" },
  "stage.draft":                    { en: "Draft",                     bn: "খসড়া" },
  "stage.quote_requested":          { en: "Quote Requested",           bn: "কোটেশন অনুরোধ করা হয়েছে" },
  "stage.quote_sent":               { en: "Quote Sent",                bn: "কোটেশন পাঠানো হয়েছে" },
  "stage.quote_accepted":           { en: "Quote Accepted",            bn: "কোটেশন গৃহীত" },
  "stage.schedule_requested":       { en: "Schedule Requested",        bn: "সময়সূচি অনুরোধ করা হয়েছে" },
  "stage.schedule_confirmed":       { en: "Schedule Confirmed",        bn: "সময়সূচি নিশ্চিত" },
  "stage.device_waiting":           { en: "Device Waiting",            bn: "ডিভাইস অপেক্ষায়" },
  "stage.device_received":          { en: "Device Received",           bn: "ডিভাইস গৃহীত" },
  "stage.inspection_waiting":       { en: "Inspection Waiting",        bn: "পরিদর্শন অপেক্ষায়" },
  "stage.inspection_started":       { en: "Inspection Started",        bn: "পরিদর্শন শুরু" },
  "stage.diagnosis_ready":          { en: "Diagnosis Ready",           bn: "ডায়াগনসিস প্রস্তুত" },
  "stage.repair_approval_required": { en: "Approval Required",         bn: "অনুমোদন প্রয়োজন" },
  "stage.repair_approved":          { en: "Repair Approved",           bn: "মেরামত অনুমোদিত" },
  "stage.repair_in_progress":       { en: "Repair In Progress",        bn: "মেরামত চলছে" },
  "stage.repair_completed":         { en: "Repair Completed",          bn: "মেরামত সম্পন্ন" },
  "stage.delivery_scheduled":       { en: "Delivery Scheduled",        bn: "ডেলিভারি নির্ধারিত" },
  "stage.delivered":                { en: "Delivered",                 bn: "ডেলিভারি সম্পন্ন" },
  "stage.cancelled":                { en: "Cancelled",                bn: "বাতিল" },
  "status.active":                  { en: "Active",                   bn: "সক্রিয়" },
  "status.pending":                 { en: "Pending",                  bn: "অপেক্ষমাণ" },
  "status.completed":               { en: "Completed",                bn: "সম্পন্ন" },
  "status.cancelled":               { en: "Cancelled",                bn: "বাতিল" },
  "status.scheduled":               { en: "Scheduled",                bn: "নির্ধারিত" },
  "status.confirmed":               { en: "Confirmed",                bn: "নিশ্চিত" },
  "status.requested":               { en: "Requested",                bn: "অনুরোধ করা হয়েছে" },
  "status.accepted":                { en: "Accepted",                 bn: "গৃহীত" },
  "status.delivered":               { en: "Delivered",                bn: "ডেলিভারি সম্পন্ন" },
  "status.ready":                   { en: "Ready",                    bn: "প্রস্তুত" },
  "status.draft":                   { en: "Draft",                    bn: "খসড়া" },
  "friendly.draft":                    { en: "We received your request. Our team will review it soon.", bn: "আমরা আপনার অনুরোধ পেয়েছি। আমাদের টিম শীঘ্রই পর্যালোচনা করবে।" },
  "friendly.quote_requested":          { en: "Your quote request is being reviewed by our team.", bn: "আপনার কোটেশন অনুরোধ আমাদের টিম পর্যালোচনা করছে।" },
  "friendly.quote_sent":               { en: "Your quote is ready. Please review and accept when convenient.", bn: "আপনার কোটেশন প্রস্তুত। সুবিধামত দেখুন ও গ্রহণ করুন।" },
  "friendly.quote_accepted":           { en: "Quote accepted! We will schedule your service shortly.", bn: "কোটেশন গৃহীত! শীঘ্রই সার্ভিস নির্ধারণ করা হবে।" },
  "friendly.schedule_requested":       { en: "Pickup requested. We will confirm a time slot shortly.", bn: "পিকআপ অনুরোধ করা হয়েছে। শীঘ্রই সময় নিশ্চিত করা হবে।" },
  "friendly.schedule_confirmed":       { en: "Your pickup is confirmed. We will be there at the scheduled time.", bn: "আপনার পিকআপ নিশ্চিত। নির্ধারিত সময়ে আমরা যাব।" },
  "friendly.device_waiting":           { en: "Your TV is waiting for inspection. No action needed from you.", bn: "আপনার TV পরিদর্শনের অপেক্ষায়। আপনার কিছু করার দরকার নেই।" },
  "friendly.device_received":          { en: "We have received your TV. It is safely in our queue.", bn: "আমরা আপনার TV পেয়েছি। এটি নিরাপদে আমাদের কাছে আছে।" },
  "friendly.inspection_waiting":       { en: "Your TV is safely in our queue.", bn: "আপনার TV নিরাপদে আমাদের সারিতে আছে।" },
  "friendly.inspection_started":       { en: "Inspection has started. We will share findings soon.", bn: "পরিদর্শন শুরু হয়েছে। শীঘ্রই ফলাফল জানাব।" },
  "friendly.diagnosis_ready":          { en: "Diagnosis is ready. Please review before repair starts.", bn: "ডায়াগনসিস প্রস্তুত। মেরামত শুরুর আগে দেখুন।" },
  "friendly.repair_approval_required": { en: "We need your approval to proceed with the repair.", bn: "মেরামত করতে আপনার অনুমোদন দরকার।" },
  "friendly.repair_approved":          { en: "Repair has been approved and will begin shortly.", bn: "মেরামত অনুমোদিত হয়েছে, শীঘ্রই শুরু হবে।" },
  "friendly.repair_in_progress":       { en: "Repair is in progress.", bn: "মেরামত চলছে।" },
  "friendly.repair_completed":         { en: "Your TV is ready!", bn: "আপনার TV প্রস্তুত!" },
  "friendly.delivery_scheduled":       { en: "Delivery is scheduled. Your TV is on its way!", bn: "ডেলিভারি নির্ধারিত। আপনার TV আসছে!" },
  "friendly.delivered":                { en: "Your TV has been delivered. Thank you!", bn: "আপনার TV ডেলিভারি হয়েছে। ধন্যবাদ!" },
  "friendly.cancelled":                { en: "This repair journey has been cancelled.", bn: "এই মেরামত যাত্রা বাতিল করা হয়েছে।" },
  "policy.privacy":      { en: "Privacy Policy",      bn: "গোপনীয়তা নীতি" },
  "policy.warranty":     { en: "Warranty Policy",     bn: "ওয়ারেন্টি নীতি" },
  "policy.terms":        { en: "Terms",               bn: "শর্তাবলি" },
  "policy.notAvailable": { en: "Policy not available", bn: "নীতি এখন পাওয়া যাচ্ছে না" },
  "policy.privacyError": { en: "The privacy policy is being updated. Contact support if you need a copy right now.", bn: "গোপনীয়তা নীতি আপডেট হচ্ছে। এখনই কপি দরকার হলে সাপোর্টে যোগাযোগ করুন।" },
  "policy.warrantyErrorTitle": { en: "Warranty details are being updated", bn: "ওয়ারেন্টির তথ্য আপডেট হচ্ছে" },
  "policy.warrantyError": { en: "Our warranty terms are temporarily unavailable. Contact support for current coverage details.", bn: "আমাদের ওয়ারেন্টি শর্ত সাময়িকভাবে পাওয়া যাচ্ছে না। বর্তমান কভারেজ জানতে সাপোর্টে যোগাযোগ করুন।" },
  "policy.termsErrorTitle": { en: "Terms are not available", bn: "শর্তাবলি এখন পাওয়া যাচ্ছে না" },
  "policy.termsError":   { en: "The terms and conditions are being refreshed. Contact support if you need help before ordering.", bn: "শর্তাবলি আপডেট হচ্ছে। অর্ডারের আগে সাহায্য দরকার হলে সাপোর্টে যোগাযোগ করুন।" },
  "policy.lastUpdated":  { en: "Last updated",        bn: "সর্বশেষ আপডেট" },

  // ── Language toggle ──
  "lang.toggle":         { en: "বাংলা",               bn: "English" },

  // ── Desktop Hero ──
  "desktop.hero.badge":          { en: "#1 Trusted Electronics Service in Bangladesh", bn: "বাংলাদেশের সেরা বিশ্বস্ত ইলেকট্রনিক্স সার্ভিস" },
  "desktop.hero.bookRepair":     { en: "Book Repair Service",                          bn: "রিপেয়ার বুক করুন" },
  "desktop.hero.browseShop":     { en: "Browse Shop",                                  bn: "শপ দেখুন" },
  "desktop.hero.trackLabel":     { en: "Check Repair Status",                          bn: "মেরামতের অবস্থা জানুন" },
  "desktop.hero.trackPlaceholder": { en: "Enter Ticket Number (e.g. TR-1234)",         bn: "টিকেট নম্বর লিখুন (যেমন TR-1234)" },
  "desktop.hero.trackBtn":       { en: "Track",                                        bn: "ট্র্যাক করুন" },
  "desktop.hero.warranty":       { en: "90-Day Warranty",                              bn: "৯০ দিনের ওয়ারেন্টি" },
  "desktop.hero.certified":      { en: "Certified Technicians",                        bn: "সার্টিফাইড টেকনিশিয়ান" },
  "desktop.hero.fast":           { en: "Fast Turnaround",                              bn: "দ্রুত সার্ভিস" },

  // ── Desktop Problems section ──
  "desktop.problems.title":      { en: "What's Wrong With Your TV?",                  bn: "আপনার TV-তে কী সমস্যা?" },
  "desktop.problems.subtitle":   { en: "Select your issue to find the right solution", bn: "সমস্যা বেছে নিন, সঠিক সমাধান পাবেন" },

  // ── Desktop Why Choose ──
  "desktop.why.title":           { en: "Why Choose Promise Electronics?",             bn: "কেন প্রমিজ ইলেকট্রনিক্স বেছে নেবেন?" },
  "desktop.why.subtitle":        { en: "We bring professionalism and transparency to the electronics service industry.", bn: "আমরা ইলেকট্রনিক্স সার্ভিসে পেশাদারিত্ব ও স্বচ্ছতা নিয়ে এসেছি।" },
  "desktop.why.f1title":         { en: "Certified Technicians",                       bn: "সার্টিফাইড টেকনিশিয়ান" },
  "desktop.why.f1desc":          { en: "Our team consists of factory-trained experts specializing in major global brands.", bn: "আমাদের টিম বিশ্বের প্রধান ব্র্যান্ডে ফ্যাক্টরি-প্রশিক্ষিত বিশেষজ্ঞদের নিয়ে গঠিত।" },
  "desktop.why.f2title":         { en: "Quick Turnaround",                            bn: "দ্রুত সার্ভিস" },
  "desktop.why.f2desc":          { en: "Priority service options available with 24-48 hour delivery for urgent repairs.", bn: "জরুরি মেরামতের জন্য ২৪-৪৮ ঘন্টার ডেলিভারিসহ প্রায়োরিটি সার্ভিস রয়েছে।" },
  "desktop.why.f3title":         { en: "Genuine Parts",                               bn: "আসল পার্টস" },
  "desktop.why.f3desc":          { en: "We use only authentic replacement parts with warranty coverage on all repairs.", bn: "সব মেরামতে শুধু আসল রিপ্লেসমেন্ট পার্টস ব্যবহার করি, ওয়ারেন্টিসহ।" },

  // ── Before/After ──
  "desktop.ba.badge":            { en: "Real Results",                                bn: "আসল ফলাফল" },
  "desktop.ba.title":            { en: "See The Difference",                          bn: "পার্থক্য দেখুন" },
  "desktop.ba.subtitle":         { en: "We bring dead TVs back to life. Check out our recent repairs.", bn: "নষ্ট TV-কে আমরা আবার জীবন্ত করি। আমাদের সাম্প্রতিক মেরামত দেখুন।" },
  "desktop.ba.fixed":            { en: "Successfully Repaired & Delivered",           bn: "সফলভাবে মেরামত ও ডেলিভারি সম্পন্ন" },

  // ── Pricing table ──
  "desktop.pricing.badge":       { en: "Transparent Pricing",                         bn: "স্বচ্ছ মূল্য" },
  "desktop.pricing.title":       { en: "No Hidden Charges. Fair & Honest Repair Costs.", bn: "কোনো লুকানো চার্জ নেই। ন্যায্য ও সৎ মেরামত মূল্য।" },
  "desktop.pricing.desc":        { en: "We believe in complete transparency. You'll know exactly what you're paying for before we start any work. Diagnosis is always free if you choose to repair with us.", bn: "আমরা সম্পূর্ণ স্বচ্ছতায় বিশ্বাস করি। কাজ শুরুর আগেই জানতে পারবেন কতটা খরচ হবে। আমাদের সাথে মেরামত করলে ডায়াগনসিস সবসময় বিনামূল্যে।" },
  "desktop.pricing.quote":       { en: "Get a Free Quote",                            bn: "ফ্রি কোটেশন নিন" },
  "desktop.pricing.contact":     { en: "Contact Us",                                  bn: "যোগাযোগ করুন" },
  "desktop.pricing.tableTitle":  { en: "Common Service Rates",                        bn: "সাধারণ সার্ভিসের রেট" },
  "desktop.pricing.footer":      { en: "* Final price depends on specific model and parts required.", bn: "* চূড়ান্ত মূল্য নির্দিষ্ট মডেল ও প্রয়োজনীয় পার্টসের উপর নির্ভর করে।" },

  // ── How It Works ──
  "desktop.how.title":           { en: "How It Works",                                bn: "কীভাবে কাজ করে" },
  "desktop.how.subtitle":        { en: "Get your TV repaired in 4 simple steps",      bn: "মাত্র ৪টি সহজ ধাপে আপনার TV মেরামত করুন" },
  "desktop.how.s1title":         { en: "Book Online",                                 bn: "অনলাইনে বুক করুন" },
  "desktop.how.s1desc":          { en: "Schedule your repair request through our website or call us directly.", bn: "ওয়েবসাইটে রিপেয়ার রিকোয়েস্ট করুন অথবা সরাসরি কল করুন।" },
  "desktop.how.s2title":         { en: "Expert Diagnosis",                            bn: "বিশেষজ্ঞ ডায়াগনসিস" },
  "desktop.how.s2desc":          { en: "Our technicians diagnose the issue and provide a transparent quote.", bn: "আমাদের টেকনিশিয়ান সমস্যা নির্ণয় করে স্বচ্ছ কোটেশন দেন।" },
  "desktop.how.s3title":         { en: "Professional Repair",                         bn: "পেশাদার মেরামত" },
  "desktop.how.s3desc":          { en: "We repair your TV using genuine parts with skilled expertise.", bn: "দক্ষতার সাথে আসল পার্টস ব্যবহার করে আপনার TV মেরামত করা হয়।" },
  "desktop.how.s4title":         { en: "Fast Delivery",                               bn: "দ্রুত ডেলিভারি" },
  "desktop.how.s4desc":          { en: "Your repaired TV is delivered back to you with warranty.", bn: "মেরামত করা TV ওয়ারেন্টিসহ আপনার কাছে ফিরিয়ে দেওয়া হয়।" },

  // ── Estimate Calculator ──
  "desktop.calc.badge":          { en: "Instant Price Estimate",                      bn: "তাৎক্ষণিক মূল্য অনুমান" },
  "desktop.calc.title":          { en: "Get an Instant Estimate",                     bn: "তাৎক্ষণিক মূল্য জানুন" },
  "desktop.calc.subtitle":       { en: "Select your TV details and see the repair price range before you book — no surprises, no hidden charges.", bn: "TV-র তথ্য বেছে নিন এবং বুক করার আগেই মেরামতের মূল্য পরিসীমা জানুন — কোনো আশ্চর্য নেই, লুকানো চার্জ নেই।" },
  "desktop.calc.labelBrand":     { en: "TV Brand",                                    bn: "TV ব্র্যান্ড" },
  "desktop.calc.labelSize":      { en: "Screen Size",                                 bn: "স্ক্রিন সাইজ" },
  "desktop.calc.labelProblem":   { en: "Problem",                                     bn: "সমস্যা" },
  "desktop.calc.resultLabel":    { en: "Estimated repair cost",                       bn: "আনুমানিক মেরামত খরচ" },
  "desktop.calc.disclaimer":     { en: "This is an estimated price range based on typical repairs. The actual cost may be slightly lower or higher depending on the true condition of your TV — and we confirm the exact figure before any work begins. If you choose not to proceed after diagnosis, you owe us nothing.", bn: "এটি সাধারণ মেরামতের ভিত্তিতে একটি আনুমানিক মূল্য পরিসীমা। প্রকৃত খরচ আপনার TV-র প্রকৃত অবস্থার উপর নির্ভর করে কিছুটা কম বা বেশি হতে পারে — কাজ শুরুর আগেই সঠিক পরিমাণ নিশ্চিত করা হয়। ডায়াগনসিসের পর এগিয়ে না যেতে চাইলে কোনো চার্জ নেই।" },
  "desktop.calc.noData":         { en: "We'll need to check this combination in person.", bn: "এই কম্বিনেশনটি আমাদের সরাসরি দেখতে হবে।" },
  "desktop.calc.noDataSub":      { en: "Contact us for a personalised quote.",         bn: "ব্যক্তিগত কোটেশনের জন্য যোগাযোগ করুন।" },
  "desktop.calc.idle":           { en: "Select all three options above to see an instant price range.", bn: "তাৎক্ষণিক মূল্য পরিসীমা দেখতে উপরের তিনটি অপশন বেছে নিন।" },
  "desktop.calc.bookThis":       { en: "Book This Repair",                            bn: "এই মেরামত বুক করুন" },
  "desktop.calc.bookGeneral":    { en: "Book a Repair",                               bn: "মেরামত বুক করুন" },

  // ── Brands ──
  "desktop.brands.title":        { en: "Brands We Service",                           bn: "আমরা যে ব্র্যান্ড সার্ভিস দিই" },
  "desktop.brands.subtitle":     { en: "Expert repair services for all major TV brands", bn: "সব প্রধান TV ব্র্যান্ডের জন্য বিশেষজ্ঞ মেরামত সার্ভিস" },

  // ── Featured Products ──
  "desktop.products.title":      { en: "Featured Products",                           bn: "বিশেষ পণ্য" },
  "desktop.products.subtitle":   { en: "Latest electronics and accessories from our collection", bn: "আমাদের সংগ্রহ থেকে সর্বশেষ ইলেকট্রনিক্স ও এক্সেসরিজ" },
  "desktop.products.viewAll":    { en: "View All Products →",                         bn: "সব পণ্য দেখুন →" },
  "desktop.products.inStock":    { en: "In Stock",                                    bn: "স্টকে আছে" },
  "desktop.products.unit":       { en: "/ unit",                                      bn: "/ পিস" },
  "desktop.products.viewDetails":{ en: "View Details",                                bn: "বিস্তারিত দেখুন" },

  // ── Team / Experts ──
  "desktop.team.title":          { en: "Meet Our Experts",                            bn: "আমাদের বিশেষজ্ঞদের সাথে পরিচিত হন" },
  "desktop.team.subtitle":       { en: "The skilled hands behind every successful repair", bn: "প্রতিটি সফল মেরামতের পেছনের দক্ষ হাত" },

  // ── Customer Reviews ──
  "desktop.reviews.title":       { en: "What Our Customers Say",                      bn: "আমাদের গ্রাহকরা কী বলেন" },
  "desktop.reviews.subtitle":    { en: "Trusted by hundreds of satisfied customers across Dhaka", bn: "ঢাকা জুড়ে শত শত সন্তুষ্ট গ্রাহকের বিশ্বাস" },
  "desktop.reviews.verified":    { en: "Verified Customer",                           bn: "যাচাইকৃত গ্রাহক" },

  // ── Service Areas ──
  "desktop.areas.title":         { en: "We Serve All Over Dhaka & Beyond",            bn: "আমরা সারা ঢাকায় সার্ভিস দিই" },
  "desktop.areas.subtitle":      { en: "Pickup and delivery services available in all major areas", bn: "সব প্রধান এলাকায় পিকআপ ও ডেলিভারি সার্ভিস রয়েছে" },

  // ── FAQ ──
  "desktop.faq.title":           { en: "Frequently Asked Questions",                  bn: "সাধারণ জিজ্ঞাসা" },
  "desktop.faq.subtitle":        { en: "Find answers to common questions about our services", bn: "আমাদের সার্ভিস সম্পর্কে সাধারণ প্রশ্নের উত্তর খুঁজুন" },

  // ── Contact ──
  "desktop.contact.title":       { en: "Get In Touch",                                bn: "যোগাযোগ করুন" },
  "desktop.contact.subtitle":    { en: "Have questions? Contact us through any of these channels", bn: "প্রশ্ন আছে? এই চ্যানেলগুলোর যেকোনো একটিতে যোগাযোগ করুন" },
  "desktop.contact.address":     { en: "Our Address",                                 bn: "আমাদের ঠিকানা" },
  "desktop.contact.phone":       { en: "Phone",                                       bn: "ফোন" },
  "desktop.contact.email":       { en: "Email",                                       bn: "ইমেইল" },
  "desktop.contact.hours":       { en: "Working Hours",                               bn: "কার্যসময়" },
  "desktop.contact.whatsapp":    { en: "Chat on WhatsApp",                            bn: "WhatsApp-এ চ্যাট করুন" },

  // ── CTA Banner ──
  "desktop.cta.title":           { en: "Have a Broken TV? Don't Throw It Away!",      bn: "TV নষ্ট? ফেলে দেবেন না!" },
  "desktop.cta.subtitle":        { en: "Get a free diagnosis today. Our experts can fix 95% of display and power issues for a fraction of the cost of a new device.", bn: "আজই বিনামূল্যে ডায়াগনসিস করুন। আমাদের বিশেষজ্ঞরা নতুন ডিভাইসের খরচের ভগ্নাংশে ৯৫% ডিসপ্লে ও পাওয়ার সমস্যা সমাধান করতে পারেন।" },
  "desktop.cta.btn":             { en: "Start Repair Request",                        bn: "মেরামতের অনুরোধ শুরু করুন" },

  "distance.interactionHint":    { en: "Drag to explore · Hold Ctrl/Cmd and scroll to zoom", bn: "\u099f\u09c7\u09a8\u09c7 \u0998\u09c1\u09b0\u09c7 \u09a6\u09c7\u0996\u09c1\u09a8 · \u099c\u09c1\u09ae \u0995\u09b0\u09a4\u09c7 Ctrl/Cmd \u099a\u09c7\u09aa\u09c7 \u09b8\u09cd\u0995\u09cd\u09b0\u09b2 \u0995\u09b0\u09c1\u09a8" },
  "distance.inspectorStatus":    { en: "Status", bn: "\u09b8\u09cd\u09a5\u09bf\u09a4\u09bf" },
  "distance.mapPreviewNote":     { en: "Coverage polygons are not published yet. Distance check and booking still work.", bn: "\u0995\u09ad\u09be\u09b0\u09c7\u099c \u09aa\u09b2\u09bf\u0997\u09a8 \u098f\u0996\u09a8\u0993 \u09aa\u09cd\u09b0\u0995\u09be\u09b6\u09bf\u09a4 \u09a8\u09df\u0964 \u09a6\u09c2\u09b0\u09a4\u09cd\u09ac \u09af\u09be\u099a\u09be\u0987 \u0993 \u09ac\u09c1\u0995\u09bf\u0982 \u098f\u0996\u09a8\u0993 \u099a\u09b2\u09ac\u09c7\u0964" },
  "distance.coverageSetupTitle": { en: "Service coverage map is being configured", bn: "\u09b8\u09be\u09b0\u09cd\u09ad\u09bf\u09b8 \u0995\u09ad\u09be\u09b0\u09c7\u099c \u09ae\u09cd\u09af\u09be\u09aa \u09aa\u09cd\u09b0\u09b8\u09cd\u09a4\u09c1\u09a4 \u09b9\u099a\u09cd\u099b\u09c7" },
  "distance.coverageSetupBody":  { en: "You can still check your distance or book a repair.", bn: "\u0986\u09aa\u09a8\u09bf \u098f\u0996\u09a8\u0993 \u09a6\u09c2\u09b0\u09a4\u09cd\u09ac \u09af\u09be\u099a\u09be\u0987 \u0995\u09b0\u09a4\u09c7 \u09ac\u09be \u09b0\u09bf\u09aa\u09c7\u09af\u09bc\u09be\u09b0 \u09ac\u09c1\u0995 \u0995\u09b0\u09a4\u09c7 \u09aa\u09be\u09b0\u09ac\u09c7\u09a8\u0964" },

  // Mobile — Why Promise Feels Different section
  "mobile.wpfd.title":           { en: "Why Promise Feels Different",                  bn: "কেন প্রমিস আলাদা?" },
  "mobile.wpfd.r1.title":        { en: "Clear estimate before repair",                 bn: "মেরামতের আগে স্পষ্ট মূল্য অনুমান" },
  "mobile.wpfd.r1.desc":         { en: "Know the cost range before we start — no surprises.", bn: "শুরুর আগেই খরচের পরিসীমা জানুন — কোনো চমক নেই।" },
  "mobile.wpfd.r2.title":        { en: "Track every repair stage",                     bn: "প্রতিটি মেরামত ধাপ ট্র্যাক করুন" },
  "mobile.wpfd.r2.desc":         { en: "Live updates from diagnosis to delivery.",      bn: "ডায়াগনসিস থেকে ডেলিভারি পর্যন্ত লাইভ আপডেট।" },
  "mobile.wpfd.r3.title":        { en: "90-day warranty on record",                    bn: "৯০ দিনের ওয়ারেন্টি — রেকর্ডে সংরক্ষিত" },
  "mobile.wpfd.r3.desc":         { en: "Written warranty accessible anytime in your account.", bn: "লিখিত ওয়ারেন্টি আপনার অ্যাকাউন্টে সবসময় সহজলভ্য।" },
  "mobile.wpfd.r4.title":        { en: "Organised pickup & delivery",                  bn: "সুশৃঙ্খল পিকআপ ও ডেলিভারি" },
  "mobile.wpfd.r4.desc":         { en: "Doorstep collection and return — no travel needed.", bn: "দরজায় সংগ্রহ ও ফেরত — যাতায়াতের ঝামেলা নেই।" },

  "distance.centerMarker":       { en: "Promise Electronics",                        bn: "প্রমিস ইলেকট্রনিক্স" },
  "distance.yourLocation":       { en: "Your private location",                      bn: "আপনার ব্যক্তিগত অবস্থান" },
  "distance.mapLabel":           { en: "Interactive distance map",                   bn: "ইন্টার‍্যাক্টিভ দূরত্ব মানচিত্র" },
  "distance.eyebrow":            { en: "Private distance check",                     bn: "ব্যক্তিগত দূরত্ব যাচাই" },
  "distance.title":              { en: "How close are we?",                          bn: "আমরা আপনার কতটা কাছে?" },
  "distance.heroTitle":          { en: "Service is closer than you think.",          bn: "সেবা আপনার ভাবনার চেয়েও কাছে।" },
  "distance.heroSubtitle":       { en: "Explore nearby service areas, check a private route, and choose the repair option that fits.", bn: "কাছাকাছি সার্ভিস এলাকা দেখুন, ব্যক্তিগত রুট যাচাই করুন এবং সহজ সার্ভিস বেছে নিন।" },
  "distance.subtitle":           { en: "Check your approximate distance, then choose a service center visit or doorstep pickup.", bn: "আনুমানিক দূরত্ব দেখুন, তারপর সার্ভিস সেন্টারে আসা বা বাসা থেকে পিকআপ বেছে নিন।" },
  "distance.resultLabel":        { en: "Approximate private distance",                bn: "আনুমানিক ব্যক্তিগত দূরত্ব" },
  "distance.kilometers":         { en: "km away",                                     bn: "কিলোমিটার দূরে" },
  "distance.metersAway":         { en: "m away",                                      bn: "মিটার দূরে" },
  "distance.almostHere":         { en: "You're almost here",                          bn: "আপনি প্রায় পৌঁছে গেছেন" },
  "distance.veryClose":          { en: "You're very close to our service center",     bn: "আপনি আমাদের সার্ভিস সেন্টারের খুব কাছে" },
  "distance.straightLineNote":   { en: "Straight-line estimate; live traffic opens in Google Maps.", bn: "এটি সরলরেখার হিসাব; লাইভ ট্রাফিক Google Maps-এ খুলবে।" },
  "distance.locating":           { en: "Finding your location...",                    bn: "আপনার অবস্থান খোঁজা হচ্ছে..." },
  "distance.findingRoute":       { en: "Finding the best route…",                     bn: "সেরা রুট খোঁজা হচ্ছে…" },
  "distance.permissionTitle":    { en: "Use your location once",                     bn: "একবার আপনার অবস্থান ব্যবহার করুন" },
  "distance.permissionBody":     { en: "Your coordinates stay in this browser and are not saved to our system.", bn: "আপনার স্থানাঙ্ক এই ব্রাউজারেই থাকবে, আমাদের সিস্টেমে সংরক্ষিত হবে না।" },
  "distance.denied":             { en: "Location permission was declined. Allow it in browser settings and try again.", bn: "লোকেশন অনুমতি দেওয়া হয়নি। ব্রাউজার সেটিংসে অনুমতি দিয়ে আবার চেষ্টা করুন।" },
  "distance.error":              { en: "We could not read your location. You can still choose a service option below.", bn: "আপনার অবস্থান পাওয়া যায়নি। নিচে থেকে সার্ভিসের ধরন বেছে নিতে পারবেন।" },
  "distance.locationFound":      { en: "Location found",                             bn: "অবস্থান পাওয়া গেছে" },
  "distance.routeUnavailable":   { en: "We found your location, but a route estimate is temporarily unavailable. You can still choose a service option.", bn: "আপনার অবস্থান পাওয়া গেছে, তবে রুটের হিসাব সাময়িকভাবে পাওয়া যাচ্ছে না। আপনি এখনও সার্ভিসের ধরন বেছে নিতে পারবেন।" },
  "distance.useLocation":        { en: "Check my distance",                          bn: "আমার দূরত্ব দেখুন" },
  "distance.checkAgain":         { en: "Check again",                                bn: "আবার দেখুন" },
  "distance.recenter":           { en: "Recenter on me",                             bn: "আমার অবস্থানে ফিরুন" },
  "distance.visitCenter":        { en: "Service center visit",                       bn: "সার্ভিস সেন্টারে আসব" },
  "distance.planVisit":          { en: "Bring the TV to us",                         bn: "টিভি আমাদের কাছে নিয়ে আসুন" },
  "distance.pickupDrop":         { en: "Pickup & drop",                              bn: "পিকআপ ও ড্রপ" },
  "distance.startPickup":        { en: "We collect from your address",               bn: "আমরা আপনার ঠিকানা থেকে সংগ্রহ করব" },
  "distance.liveDirections":     { en: "Open live directions",                       bn: "লাইভ দিকনির্দেশনা খুলুন" },
  "distance.privacy":            { en: "Privacy: your location is used temporarily for this route estimate and is never stored in our system.", bn: "গোপনীয়তা: আপনার অবস্থান শুধু এই রুটের হিসাবের জন্য সাময়িকভাবে ব্যবহৃত হবে এবং আমাদের সিস্টেমে সংরক্ষণ করা হবে না।" },
  "distance.searchAreas":        { en: "Search area, sector or block", bn: "এলাকা, সেক্টর বা ব্লক খুঁজুন" },
  "distance.noAreaMatch":        { en: "No matching service area. Try Gulshan, Banani, or Dhanmondi.", bn: "কোনো মিল পাওয়া যায়নি। গুলশান, বনানী বা ধানমন্ডি লিখে দেখুন।" },
  "distance.cantFindPlace":      { en: "We can't find that place. Check the spelling or try a nearby landmark.", bn: "সেই স্থান খুঁজে পাওয়া যায়নি। বানান ঠিক আছে কিনা দেখুন অথবা কাছের কোনো পরিচিত জায়গা লিখুন।" },
  "distance.noPublishedAreas":   { en: "No published service areas yet. Distance check still works.", bn: "এখনও কোনো প্রকাশিত সার্ভিস এলাকা নেই। দূরত্ব যাচাই এখনও চালু আছে।" },
  "distance.searchHint":         { en: "Search address, building or area", bn: "ঠিকানা, ভবন বা এলাকা খুঁজুন" },
  "distance.serviceAreaResults": { en: "Service areas", bn: "সার্ভিস এলাকা" },
  "distance.addressResults":     { en: "Places and addresses", bn: "স্থান ও ঠিকানা" },
  "distance.searchingPlaces":    { en: "Searching places...", bn: "স্থান খোঁজা হচ্ছে..." },
  "distance.placeSearchUnavailable": { en: "Address search is temporarily unavailable.", bn: "ঠিকানা অনুসন্ধান সাময়িকভাবে বন্ধ আছে।" },
  "distance.chooseArea":         { en: "Tap a service area to see how often we work nearby.", bn: "আপনার কাছাকাছি আমরা কতবার কাজ করি তা দেখতে একটি সার্ভিস এলাকা চাপুন।" },
  "distance.minutesEstimate":    { en: "min estimated", bn: "মিনিট আনুমানিক" },
  "distance.fallbackRoute":      { en: "Approximate direct distance — road route unavailable.", bn: "আনুমানিক সরাসরি দূরত্ব — সড়ক রুট পাওয়া যায়নি।" },
  "distance.roadRouteLabel":     { en: "Road route via OpenRouteService", bn: "OpenRouteService সড়ক রুট" },
  "distance.demandNew":          { en: "New service area", bn: "নতুন সার্ভিস এলাকা" },
  "distance.demand5Plus":        { en: "5+ requests from this area", bn: "এই এলাকা থেকে ৫টির বেশি অনুরোধ" },
  "distance.demand20Plus":       { en: "20+ requests from this area", bn: "এই এলাকা থেকে ২০টির বেশি অনুরোধ" },
  "distance.demand50Plus":       { en: "50+ requests from this area", bn: "এই এলাকা থেকে ৫০টির বেশি অনুরোধ" },
  "distance.zoomIn":             { en: "Zoom in",                                    bn: "জুম ইন" },
  "distance.zoomOut":            { en: "Zoom out",                                   bn: "জুম আউট" },
  "distance.mapHint":            { en: "Drag to pan · tap + / − to zoom",           bn: "টেনে সরান · + / − দিয়ে জুম করুন" },
  "distance.areaListUnavailable": { en: "Area details are temporarily unavailable. Repair booking still works.", bn: "এলাকার তথ্য সাময়িকভাবে পাওয়া যাচ্ছে না। রিপেয়ার বুকিং চালু আছে।" },
  "wizard.serviceArea":          { en: "Service area (optional)", bn: "সার্ভিস এলাকা (ঐচ্ছিক)" },
  "wizard.serviceAreaHint":      { en: "Choose your area for a more accurate pickup plan.", bn: "আরও নির্ভুল পিকআপ পরিকল্পনার জন্য আপনার এলাকা বেছে নিন।" },
  "wizard.noServiceArea":        { en: "Continue without selecting an area", bn: "এলাকা নির্বাচন না করে এগিয়ে যান" },
  "wizard.submittingTitle":      { en: "Placing your service request", bn: "আপনার সার্ভিস অনুরোধ পাঠানো হচ্ছে" },
  "wizard.submittingBody":       { en: "Securing your details and preparing your ticket...", bn: "আপনার তথ্য সুরক্ষিত করে টিকেট প্রস্তুত করা হচ্ছে..." },
  "wizard.areaSuccessPrefix":    { en: "We regularly serve customers around", bn: "আমরা নিয়মিত গ্রাহকদের সেবা দিই" },
} as const;

export type TranslationKey = keyof typeof translations;

interface CustomerLanguageContextValue {
  language: CustomerLang;
  setLanguage: (lang: CustomerLang) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
}

const CustomerLanguageContext = createContext<CustomerLanguageContextValue | null>(null);

function getInitialLang(): CustomerLang {
  if (typeof window === "undefined") return "en";
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "bn" ? "bn" : "en";
}

export function CustomerLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<CustomerLang>(getInitialLang);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dataset.customerLang = language;
  }, [language]);

  const setLanguage = useCallback((lang: CustomerLang) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((prev) => {
      const next = prev === "en" ? "bn" : "en";
      localStorage.setItem(STORAGE_KEY, next);
      return next;
    });
  }, []);

  const t = useCallback(
    (key: TranslationKey): string => translations[key]?.[language] ?? key,
    [language],
  );

  return (
    <CustomerLanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </CustomerLanguageContext.Provider>
  );
}

export function useCustomerLanguage() {
  const ctx = useContext(CustomerLanguageContext);
  if (!ctx) throw new Error("useCustomerLanguage must be used inside CustomerLanguageProvider");
  return ctx;
}
